apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: chearghipour/notification:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000  # FastAPI
        - containerPort: 8765  # WebSocket
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: kafka
spec:
  selector:
    app: notification
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: websocket
      port: 8765
      targetPort: 8765
