apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  namespace: kafka
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
      - name: spark-worker
        image: cheraghipour/spark:latest
        env:
        - name: SPARK_MODE
          value: worker
        - name: SPARK_MASTER_URL
          value: spark://spark-master1.kafka.svc.cluster.local:7077
        ports:
        - containerPort: 8081
