

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Trading_Signal_Service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: signal-generator
  template:
    metadata:
      labels:
        app: signal-generator
    spec:
      containers:
      - name: signal-generator
        image: cheraghipour/Trading_Signal_Service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000  
        - containerPort: 8765 
